# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 12:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20180215_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creater',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
