# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20180301_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
